trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '6.x'

stages:
  - stage: Restore_and_Build
    jobs:
      - job: Run_Continuous_Integration_Tasks
        steps:
        - task: UseDotNet@2        
          displayName: 'Use .NET SDK $(dotnetSdkVersion)'
          inputs:
            version: $(dotnetSdkVersion)

        - script: |
            dotnet restore
          displayName: Install dependencies

        - script: |
            dotnet test
          displayName: Run unit tests

        - script: |
            dotnet publish --no-restore --configuration Release --output ./artifact
          displayName: Build & package (.zip file)

        - script: |
            cp -r ./* artifact
            zip -r artifact.zip ./artifact
          displayName: Create a .ZIP file artifact

        - task: PublishBuildArtifacts@1
          displayName: Publish build artifact (.zip file)
          inputs:
            pathToPublish: './artifact.zip'
            artifactName: artifact

            


